### ISSUE TITLE
Training model on cifar10 dataset.

### ISSUE THREAD

**Issue by sssongrm** [JegZheng/truncated-diffusion-probabilistic-models#2]
I want to train the model on cifar10 dataset, but the following error occurs:

python3 main.py --config cifar10.yml --exp /home/test/truncated-diffusion-probabilistic-models-main --doc model1

ERROR - main.py - Traceback (most recent call last):
  File "main.py", line 221, in main
    runner.train()
  File "/home/test/truncated-diffusion-probabilistic-models-main/runners/diffusion.py", line 229, in train
    x_fake_logits = discriminator(x_gen_prime_implicit, c=0)
  File "/home/test/miniconda3/envs/test/lib/python3.8/site-packages/torch/nn/modules/module.py", line 1190, in _call_impl
    return forward_call(*input, **kwargs)
  File "/home/test/miniconda3/envs/test/lib/python3.8/site-packages/torch/nn/parallel/data_parallel.py", line 169, in forward
    return self.module(*inputs[0], **kwargs[0])
  File "/home/test/miniconda3/envs/test/lib/python3.8/site-packages/torch/nn/modules/module.py", line 1190, in _call_impl
    return forward_call(*input, **kwargs)
  File "/home/test/songruimin/truncated-diffusion/truncated-diffusion-probabilistic-models-main/models/diffusion.py", line 574, in forward
    x = self.b4(x, img, cmap)
  File "/home/test/miniconda3/envs/test/lib/python3.8/site-packages/torch/nn/modules/module.py", line 1190, in _call_impl
    return forward_call(*input, **kwargs)
  File "/home/test/truncated-diffusion-probabilistic-models-main/models/diffusion.py", line 508, in forward
    x = self.out(x)
  File "/home/test/miniconda3/envs/test/lib/python3.8/site-packages/torch/nn/modules/module.py", line 1190, in _call_impl
    return forward_call(*input, **kwargs)
  File "/home/test/truncated-diffusion-probabilistic-models-main/models/diffusion.py", line 675, in forward
    x = torch.addmm(b.unsqueeze(0), x, w.t())
RuntimeError: CUDA error: CUBLAS_STATUS_INVALID_VALUE when calling `cublasSgemm( handle, opa, opb, m, n, k, &alpha, a, lda, b, ldb, &beta, c, ldc)`

Please tell me how to run the code correctly?

**Comment by JegZheng** [comment]
> I want to train the model on cifar10 dataset, but the following error occurs:
> 
> python3 main.py --config cifar10.yml --exp /home/test/truncated-diffusion-probabilistic-models-main --doc model1
> 
> ERROR - main.py - Traceback (most recent call last): File "main.py", line 221, in main runner.train() File "/home/test/truncated-diffusion-probabilistic-models-main/runners/diffusion.py", line 229, in train x_fake_logits = discriminator(x_gen_prime_implicit, c=0) File "/home/test/miniconda3/envs/test/lib/python3.8/site-packages/torch/nn/modules/module.py", line 1190, in _call_impl return forward_call(*input, **kwargs) File "/home/test/miniconda3/envs/test/lib/python3.8/site-packages/torch/nn/parallel/data_parallel.py", line 169, in forward return self.module(*inputs[0], **kwargs[0]) File "/home/test/miniconda3/envs/test/lib/python3.8/site-packages/torch/nn/modules/module.py", line 1190, in _call_impl return forward_call(*input, **kwargs) File "/home/test/songruimin/truncated-diffusion/truncated-diffusion-probabilistic-models-main/models/diffusion.py", line 574, in forward x = self.b4(x, img, cmap) File "/home/test/miniconda3/envs/test/lib/python3.8/site-packages/torch/nn/modules/module.py", line 1190, in _call_impl return forward_call(*input, **kwargs) File "/home/test/truncated-diffusion-probabilistic-models-main/models/diffusion.py", line 508, in forward x = self.out(x) File "/home/test/miniconda3/envs/test/lib/python3.8/site-packages/torch/nn/modules/module.py", line 1190, in _call_impl return forward_call(*input, **kwargs) File "/home/test/truncated-diffusion-probabilistic-models-main/models/diffusion.py", line 675, in forward x = torch.addmm(b.unsqueeze(0), x, w.t()) RuntimeError: CUDA error: CUBLAS_STATUS_INVALID_VALUE when calling `cublasSgemm( handle, opa, opb, m, n, k, &alpha, a, lda, b, ldb, &beta, c, ldc)`
> 
> Please tell me how to run the code correctly?

Hi, I cannot reproduce this CUDA error. Could you provide more information about your environment?

**Comment by sssongrm** [comment]
***@***.******@***.***
